# --- App ---
spring.application.name=inventory-api
server.port=8080


# JPA + SQLite
spring.datasource.url=jdbc:sqlite:./data/inventory.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# --- RabbitMQ (central bus de eventos) ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.messaging.exchange=inventory.events.exchange
app.messaging.queue=inventory.events.queue
app.messaging.routing-key=inventory.events.key

# --- Logs ---
logging.level.org.springframework=INFO
logging.level.com.acme.inventory=DEBUG